comm_range: 30.0
sigmaDst: 0.5
sigmaOri: 0.05 #about 2.5 deg
biasDst: 0.0
biasOri: 0.0
beacon_up_topic: beacon_up_topic
beacon_down_topic: beacon_down_topic
sync_up_topic: sync_up_topic
sync_down_topic: sync_down_topic
data_up_topic: data_up_topic
data_down_topic: data_down_topic
submap_up_topic: submap_up_topic
submap_down_topic: submap_down_topic
submap_ack_up_topic: submap_ack_up_topic
submap_ack_down_topic: submap_ack_down_topic

spawn_service_name: spawn_robot
first_robot_autostart: true

# The distance of the last robot from the base divided by comm_range
# Once the ratio reaches this value, a new robot is spawned.
ratio_spawn_comm: 0.35
